### ISSUE TITLE
FOMM cam_fomm.py FileNotFoundError

### ISSUE THREAD

**Issue by PeterKW** [AliaksandrSiarohin/first-order-model#117]
Traceback (most recent call last):
  File "D:\miniconda3\avatarify\fomm\cam_fomm.py", line 217, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, device=device)
  File "D:\miniconda3\avatarify\fomm\cam_fomm.py", line 34, in load_checkpoints
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'fomm/config/vox-adv-256.yaml'

Any idea how I should try and fix this error? I'm not sure why it can't find the file?

Thank you very much
![image](https://user-images.githubusercontent.com/13779157/80013883-7d135a00-84c7-11ea-9f0f-2912a68141f8.png)

**Comment by AliaksandrSiarohin** [comment]
You are launching from the wrong folder most likely, try to specify absolute path instead of relative.

**Comment by PeterKW** [comment]
I'm not quite sure where else I could be running it from? It may be that I have misunderstood something?  

(base) D:\miniconda3>run_windows.bat
load checkpoints..
Traceback (most recent call last):
File "D:\miniconda3\avatarify\fomm\cam_fomm.py", line 217, in
generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, device=device)
File "D:\miniconda3\avatarify\fomm\cam_fomm.py", line 34, in load_checkpoints
with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'fomm/config/vox-adv-256.yaml'

I have vox-adv-cpk.pth.tar at D:\miniconda3\avatarify not sure if that is related to the file that it cannot find? 
https://github.com/alievk/avatarify/

I'm only a student developer so I haven't done much of this before but it would be great if I could get it to work. Thank you very much
