### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by NikOol172** [AliaksandrSiarohin/first-order-model#169]
Hello,

what is the minimal GPU memory needed for training taichi model using png`s ?

$ CUDA_VISIBLE_DEVICES=0 python run.py --config config/taichi-256.yaml --device_ids 0
In /home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In /home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In /home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Use predefined train-test split.
Training...
  0%|                                                                                                                                                           | 0/100 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/home/nickhoule/first-order-model/train.py", line 51, in train
    losses_generator, generated = generator_full(x)
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nickhoule/first-order-model/modules/model.py", line 155, in forward
    generated = self.generator(x['source'], kp_source=kp_source, kp_driving=kp_driving)
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nickhoule/first-order-model/modules/generator.py", line 63, in forward
    out = self.down_blocks[i](out)
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nickhoule/first-order-model/modules/util.py", line 112, in forward
    out = F.relu(out)
  File "/home/nickhoule/anaconda3/envs/first-order-model/lib/python3.7/site-packages/torch/nn/functional.py", line 643, in relu
    return torch.relu(input)
RuntimeError: CUDA error: out of memory

$ nvidia-smi
Tue Jun 30 19:22:49 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P8     6W /  75W |      0MiB /  7611MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by AliaksandrSiarohin** [comment]
It depends on batch size. Set smaller batch size.
