### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by NekoKazumi** [AliaksandrSiarohin/first-order-model#172]
I tried to install the requirements.txt but i got this error and I dont know what to do with it

```
ERROR: Command errored out with exit status 1:
     command: 'c:\users\neko\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Neko\\AppData\\Local\\Temp\\pip-install-k4dh5k5e\\cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Neko\\AppData\\Local\\Temp\\pip-install-k4dh5k5e\\cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Neko\AppData\Local\Temp\pip-pip-egg-info-auk_p4cg'
         cwd: C:\Users\Neko\AppData\Local\Temp\pip-install-k4dh5k5e\cffi\
    Complete output (30 lines):
    Traceback (most recent call last):
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Neko\AppData\Local\Temp\pip-install-k4dh5k5e\cffi\setup.py", line 120, in <module>
        if sys.platform == 'win32' and uses_msvc():
      File "C:\Users\Neko\AppData\Local\Temp\pip-install-k4dh5k5e\cffi\setup.py", line 98, in uses_msvc
        return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 327, in compile
        self.initialize()
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\neko\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by LeCyberDucky** [comment]
Looks like you need to install the [Visual C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/).
