### ISSUE TITLE
Crop video error

### ISSUE THREAD

**Issue by xiaodhu** [AliaksandrSiarohin/first-order-model#174]
Hi @AliaksandrSiarohin ,

I met an error when I used crop_video.py to process my own video file.

`python3 crop-video.py --inp test.mp4
0it [00:00, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument

Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 96, in process_video
    bboxes =  extract_bbox(frame, fa)
  File "crop-video.py", line 22, in extract_bbox
    bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])
  File "/usr/local/lib/python3.6/dist-packages/face_alignment-1.0.1-py3.6.egg/face_alignment/detection/sfd/sfd_detector.py", line 34, in detect_from_image
  File "/usr/local/lib/python3.6/dist-packages/face_alignment-1.0.1-py3.6.egg/face_alignment/detection/sfd/detect.py", line 30, in detect
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/face_alignment-1.0.1-py3.6.egg/face_alignment/detection/sfd/net_s3fd.py", line 71, in forward
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405
Fatal Python error: could not acquire lock for <_io.BufferedReader name=28> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007fe4a0b8d700 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/imageio_ffmpeg/_parsing.py", line 61 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fe52c292740 (most recent call first):
  File "/usr/lib/python3.6/subprocess.py", line 1537 in _communicate
  File "/usr/lib/python3.6/subprocess.py", line 843 in communicate
  File "/usr/local/lib/python3.6/dist-packages/imageio_ffmpeg/_io.py", line 193 in read_frames
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py", line 342 in _close
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 252 in close
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/format.py", line 241 in __del__
Aborted (core dumped)`

Also tried to add --min_frames parameter to some lower number, but not be helpful. The original video is 640x480 resolution, 30 fps. Any suggestion?

Thanks a lot
Xiaodong

**Comment by xiaodhu** [comment]
Re-installed pytorch, issued resolved.

**Comment by HanTnx** [comment]
Hello. I meet the same error that I had. I saw your solution to re-installed pytorch. Can you tell me what version of pytorch did you installed? Thank you in advance.
