### ISSUE TITLE
MemoryError with demo.py

### ISSUE THREAD

**Issue by Bardo-Konrad** [AliaksandrSiarohin/first-order-model#177]
```
python demo.py  --config config\vox-256.yaml --driving_video "G:\tmp\crop01.mp4" --source_image "source.jpg" --checkpoint checkpoints\vox-cpk.pth.tar --relative --adapt_scale
E:\Anaconda\envs\fom\lib\site-packages\dask\config.py:129: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
E:\Anaconda\envs\fom\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
E:\Anaconda\envs\fom\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 155, in <module>
    predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale, cpu=opt.cpu)
  File "demo.py", line 63, in make_animation
    driving = torch.tensor(np.array(driving_video)[np.newaxis].astype(np.float32)).permute(0, 4, 1, 2, 3)
MemoryError
```

Solutions? Is cuda used there?

**Comment by Bardo-Konrad** [comment]
I used a much smaller video file with a 256 x 256 image. Now it worked. 

1. How do I extend this? 
2. What is meant by MemoryError? Swap file size?
3. How do I make it use cuda?

**Comment by japanvik** [comment]
The original code loads the whole video into memory, so if you use a large or long video, your workstation will run out, and get a MemoryError. This is your regular RAM size and not your video card RAM size.

I had to refactor make_animation and separated out the processing steps in order to run the forward pass frame by frame, thus allowing for much larger and longer videos to be pushed through the forward pass. Also this allows me to do more image manipulation work on a frame level so, like cropping, rotating etc.

Not too difficult if you get into demo.py and spend some time tracing what it's doing.
 
> I used a much smaller video file with a 256 x 256 image. Now it worked.
> 
> 1. How do I extend this?
> 2. What meant by MemoryError? Swap file size?
> 3. How do I make it use cuda?

**Comment by Bardo-Konrad** [comment]
Mind sharing your demo.py?

**Comment by japanvik** [comment]
Sure.
It's not much - just a re-creation of demo.py's "make_animation" by replacing 
```
imageio.mimread
```
with
```
imageio.get_reader
```
for the driving video so that the process can be iterated frame by frame. I don't have all the Google drive stuff because I'm running this locally, but it should work if you stick it into the repo root and adjust the filenames accordingly.

https://gist.github.com/japanvik/71313bbcdb9eb099492bc6a8094abe8c

Hopefully self explanatory but let me know if you have any questions.

**Comment by Bardo-Konrad** [comment]
I had to replace

```
from tqdm import notebook
for frame in notebook.tqdm(driving_video, total=int(ttl)):
```

with

```
from tqdm import tqdm
for frame in tqdm(driving_video, total=int(ttl)):
```

for it to work. It worked with a short clip that previously caused a memory error.

How do I define dimensions other than 256 x 256 as output, for instance when the input image is 640 x 360 and the output should be the same without distortion...

**Comment by japanvik** [comment]
> how do I define dimensions other than 256 x 256 as output, for instance when the input image is 640 x 360 and the output should be the same without distortion...

You're better off asking @AliaksandrSiarohin about that, but I think the network in the repo only takes 256x256 and outputs 256x256. Even if you manage to push through a 640x360, unless you are re-training the network, you probably won't get good results because the network is not designed for it.

You could crop the region of interest (like the face region) with a size of 256x256, pass it through the network, and paste it back on to the original image to get your new result tho.

**Comment by Bardo-Konrad** [comment]
Yes, the idea of cropping the region of interest worked well for me.

@AliaksandrSiarohin I would like to include Hand Gestures aswell, so the whole upper body of a person sitting at a desk. What would training look like, which properties should the input have?

And finally:

@AliaksandrSiarohin Very impressive work.
