### ISSUE TITLE
I have an error for crop-video.py

### ISSUE THREAD

**Issue by alemsas** [AliaksandrSiarohin/first-order-model#180]
hi
i have this error whene i try to use crop-video.py
but when i try this by another video it solves!
what is my mistake?

`690it [01:40,  6.87it/s]Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\imageio\plugins\ffmpeg.py", line 565, in _read_frame_data
    (len(s), framesize))
RuntimeError: Frame is 0 bytes, but expected 2764800.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 94, in process_video
    for i, frame in tqdm(enumerate(video)):
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\tqdm\_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\imageio\core\format.py", line 397, in iter_data
    im, meta = self._get_data(i)
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\imageio\plugins\ffmpeg.py", line 396, in _get_data
    result, is_new = self._read_frame()
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\imageio\plugins\ffmpeg.py", line 585, in _read_frame
    s, is_new = self._read_frame_data()
  File "d:\ProgramData\Anaconda3\envs\deefake\lib\site-packages\imageio\plugins\ffmpeg.py", line 571, in _read_frame_data
    raise CannotReadFrameError(fmt % (self._pos, err1, err2))
imageio.core.format.CannotReadFrameError: Could not read frame 689:
Frame is 0 bytes, but expected 2764800.
=== stderr ===
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Myanimate\assets\720.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2020-07-12T19:35:32.000000Z
  Duration: 00:00:23.06, start: 0.000000, bitrate: 12136 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 11954 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:

      creation_time   : 2020-07-12T19:35:32.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2020-07-12T19:35:32.000000Z
      handler_name    : #Mainconcept MP4 Sound Media Handler

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1280x720, q=2-31, 663552 kb/s, 30 fps, 30 tbn, 30 tbc (default)
... showing only last few lines ...
frame=  471 fps=6.8 q=-0.0 size= 1271700kB time=00:00:15.70 bitrate=663552.0kbits/s speed=0.225x
frame=  475 fps=6.8 q=-0.0 size= 1282500kB time=00:00:15.83 bitrate=663552.0kbits/s speed=0.225x
frame=  479 fps=6.8 q=-0.0 size= 1293300kB time=00:00:15.96 bitrate=663552.0kbits/s speed=0.225x
frame=  483 fps=6.8 q=-0.0 size= 1304100kB time=00:00:16.10 bitrate=663552.0kbits/s speed=0.225x
frame=  487 fps=6.8 q=-0.0 size= 1314900kB time=00:00:16.23 bitrate=663552.0kbits/s speed=0.225x
frame=  491 fps=6.8 q=-0.0 size= 1325700kB time=00:00:16.36 bitrate=663552.0kbits/s speed=0.225x
frame=  495 fps=6.8 q=-0.0 size= 1336500kB time=00:00:16.50 bitrate=663552.0kbits/s speed=0.225x
frame=  499 fps=6.8 q=-0.0 size= 1347300kB time=00:00:16.63 bitrate=663552.0kbits/s speed=0.226x
frame=  503 fps=6.8 q=-0.0 size= 1358100kB time=00:00:16.76 bitrate=663552.0kbits/s speed=0.226x
frame=  507 fps=6.8 q=-0.0 size= 1368900kB time=00:00:16.90 bitrate=663552.0kbits/s speed=0.226x
frame=  511 fps=6.8 q=-0.0 size= 1379700kB time=00:00:17.03 bitrate=663552.0kbits/s speed=0.226x
frame=  515 fps=6.8 q=-0.0 size= 1390500kB time=00:00:17.16 bitrate=663552.0kbits/s speed=0.226x
frame=  519 fps=6.8 q=-0.0 size= 1401300kB time=00:00:17.30 bitrate=663552.0kbits/s speed=0.226x
frame=  523 fps=6.8 q=-0.0 size= 1412100kB time=00:00:17.43 bitrate=663552.0kbits/s speed=0.226x
frame=  527 fps=6.8 q=-0.0 size= 1422900kB time=00:00:17.56 bitrate=663552.0kbits/s speed=0.226x
frame=  531 fps=6.8 q=-0.0 size= 1433700kB time=00:00:17.70 bitrate=663552.0kbits/s speed=0.226x
frame=  535 fps=6.8 q=-0.0 size= 1444500kB time=00:00:17.83 bitrate=663552.0kbits/s speed=0.226x
frame=  539 fps=6.8 q=-0.0 size= 1455300kB time=00:00:17.96 bitrate=663552.0kbits/s speed=0.226x
frame=  543 fps=6.8 q=-0.0 size= 1466100kB time=00:00:18.10 bitrate=663552.0kbits/s speed=0.226x
frame=  547 fps=6.8 q=-0.0 size= 1476900kB time=00:00:18.23 bitrate=663552.0kbits/s speed=0.226x
frame=  551 fps=6.8 q=-0.0 size= 1487700kB time=00:00:18.36 bitrate=663552.0kbits/s speed=0.226x
frame=  555 fps=6.8 q=-0.0 size= 1498500kB time=00:00:18.50 bitrate=663552.0kbits/s speed=0.226x
frame=  559 fps=6.8 q=-0.0 size= 1509300kB time=00:00:18.63 bitrate=663552.0kbits/s speed=0.226x
frame=  563 fps=6.8 q=-0.0 size= 1520100kB time=00:00:18.76 bitrate=663552.0kbits/s speed=0.227x
frame=  567 fps=6.8 q=-0.0 size= 1530900kB time=00:00:18.90 bitrate=663552.0kbits/s speed=0.227x
frame=  571 fps=6.8 q=-0.0 size= 1541700kB time=00:00:19.03 bitrate=663552.0kbits/s speed=0.227x
frame=  575 fps=6.8 q=-0.0 size= 1552500kB time=00:00:19.16 bitrate=663552.0kbits/s speed=0.227x
frame=  579 fps=6.8 q=-0.0 size= 1563300kB time=00:00:19.30 bitrate=663552.0kbits/s speed=0.227x
frame=  583 fps=6.8 q=-0.0 size= 1574100kB time=00:00:19.43 bitrate=663552.0kbits/s speed=0.227x
frame=  587 fps=6.8 q=-0.0 size= 1584900kB time=00:00:19.56 bitrate=663552.0kbits/s speed=0.227x
frame=  591 fps=6.8 q=-0.0 size= 1595700kB time=00:00:19.70 bitrate=663552.0kbits/s speed=0.227x
frame=  595 fps=6.8 q=-0.0 size= 1606500kB time=00:00:19.83 bitrate=663552.0kbits/s speed=0.227x
frame=  599 fps=6.8 q=-0.0 size= 1617300kB time=00:00:19.96 bitrate=663552.0kbits/s speed=0.227x
frame=  603 fps=6.8 q=-0.0 size= 1628100kB time=00:00:20.10 bitrate=663552.0kbits/s speed=0.227x
frame=  607 fps=6.8 q=-0.0 size= 1638900kB time=00:00:20.23 bitrate=663552.0kbits/s speed=0.227x
frame=  611 fps=6.8 q=-0.0 size= 1649700kB time=00:00:20.36 bitrate=663552.0kbits/s speed=0.227x
frame=  615 fps=6.8 q=-0.0 size= 1660500kB time=00:00:20.50 bitrate=663552.0kbits/s speed=0.227x
frame=  619 fps=6.8 q=-0.0 size= 1671300kB time=00:00:20.63 bitrate=663552.0kbits/s speed=0.227x
frame=  623 fps=6.8 q=-0.0 size= 1682100kB time=00:00:20.76 bitrate=663552.0kbits/s speed=0.227x
frame=  627 fps=6.8 q=-0.0 size= 1692900kB time=00:00:20.90 bitrate=663552.0kbits/s speed=0.227x
frame=  631 fps=6.8 q=-0.0 size= 1703700kB time=00:00:21.03 bitrate=663552.0kbits/s speed=0.227x
frame=  635 fps=6.8 q=-0.0 size= 1714500kB time=00:00:21.16 bitrate=663552.0kbits/s speed=0.228x
frame=  639 fps=6.8 q=-0.0 size= 1725300kB time=00:00:21.30 bitrate=663552.0kbits/s speed=0.228x
frame=  643 fps=6.8 q=-0.0 size= 1736100kB time=00:00:21.43 bitrate=663552.0kbits/s speed=0.228x
frame=  647 fps=6.8 q=-0.0 size= 1746900kB time=00:00:21.56 bitrate=663552.0kbits/s speed=0.228x
frame=  651 fps=6.8 q=-0.0 size= 1757700kB time=00:00:21.70 bitrate=663552.0kbits/s speed=0.228x
frame=  655 fps=6.8 q=-0.0 size= 1768500kB time=00:00:21.83 bitrate=663552.0kbits/s speed=0.228x
frame=  659 fps=6.8 q=-0.0 size= 1779300kB time=00:00:21.96 bitrate=663552.0kbits/s speed=0.228x
frame=  663 fps=6.8 q=-0.0 size= 1790100kB time=00:00:22.10 bitrate=663552.0kbits/s speed=0.228x
frame=  667 fps=6.8 q=-0.0 size= 1800900kB time=00:00:22.23 bitrate=663552.0kbits/s speed=0.228x
frame=  671 fps=6.8 q=-0.0 size= 1811700kB time=00:00:22.36 bitrate=663552.0kbits/s speed=0.228x
frame=  675 fps=6.8 q=-0.0 size= 1822500kB time=00:00:22.50 bitrate=663552.0kbits/s speed=0.228x
frame=  679 fps=6.8 q=-0.0 size= 1833300kB time=00:00:22.63 bitrate=663552.0kbits/s speed=0.228x
frame=  683 fps=6.8 q=-0.0 size= 1844100kB time=00:00:22.76 bitrate=663552.0kbits/s speed=0.228x
frame=  687 fps=6.8 q=-0.0 size= 1854900kB time=00:00:22.90 bitrate=663552.0kbits/s speed=0.228x
frame=  690 fps=6.8 q=-0.0 size= 1863000kB time=00:00:23.00 bitrate=663552.0kbits/s speed=0.228x
frame=  690 fps=6.8 q=-0.0 Lsize= 1863000kB time=00:00:23.00 bitrate=663552.0kbits/s speed=0.228x
video:1863000kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%`

**Comment by AliaksandrSiarohin** [comment]
#197
