### ISSUE TITLE
OSError: [WinError 126]

### ISSUE THREAD

**Issue by xxxdakevingame** [AliaksandrSiarohin/first-order-model#183]
When trying to use the crop video script i get this error
(FO2) C:\Games\deepfake\first-order-model>python crop-video.py --inp driving_video\council.mp4
Traceback (most recent call last):
  File "crop-video.py", line 1, in <module>
    import face_alignment
  File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\face_alignment\__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\face_alignment\api.py", line 3, in <module>
    import torch
  File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\Kevin\anaconda3\envs\FO2\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by zhuyinna** [comment]
> When trying to use the crop video script i get this error (FO2) C:\Games\deepfake\first-order-model>python crop-video.py --inp driving_video\council.mp4 Traceback (most recent call last): File "crop-video.py", line 1, in import face_alignment File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\face_alignment__init__.py", line 7, in from .api import FaceAlignment, LandmarksType, NetworkSize File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\face_alignment\api.py", line 3, in import torch File "C:\Users\Kevin\anaconda3\envs\FO2\lib\site-packages\torch__init__.py", line 81, in ctypes.CDLL(dll) File "C:\Users\Kevin\anaconda3\envs\FO2\lib\ctypes__init__.py", line 348, in **init** self._handle = _dlopen(self._name, mode) OSError: [WinError 126] The specified module could not be found

I meet the same problem. have you resolved this problem?
