### ISSUE TITLE
THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=47 error=999 : unknown error

### ISSUE THREAD

**Issue by CookidNA** [AliaksandrSiarohin/first-order-model#185]
I get this error when running either the demo or the face alignment:

> THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=47 error=999 : unknown error
Traceback (most recent call last):
  File "demo.py", line 144, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 32, in load_checkpoints
    generator.cuda()
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 203, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 225, in _apply
    param_applied = fn(param)
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\nn\modules\module.py", line 307, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "D:\program files\anaconda\envs\FO2\lib\site-packages\torch\cuda\__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (999) : unknown error at ..\aten\src\THC\THCGeneral.cpp:47

Looking through sites where people had the same issue (on different programs), my conclusion is that you can't run this without an NVIDIA card for cuda. So an easier question: does this only run on nvidia cards? I don't see anywhere in the page that nvidia is required, but it uses cuda which states it's nvidia only. I might just be stupid so I just want to make sure.

**Comment by AliaksandrSiarohin** [comment]
Yes, nvidia card is required. Alternatively you can use cpu for demo.

**Comment by CookidNA** [comment]
> Yes, nvidia card is required. Alternatively you can use cpu for demo.

Alright, thank you for the clarification. Are there any instructions on how to use cpu instead?

**Comment by AliaksandrSiarohin** [comment]
Add ```--cpu``` flag.

**Comment by CookidNA** [comment]
> Add `--cpu` flag.
I feel stupid for not knowing that, but thank you! No remaining issues.

**Comment by arcillus** [comment]
So, where to put the --cpu flag? I'm sorry about my questions.
