### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jysa01** [AliaksandrSiarohin/first-order-model#188]
Hello, 
Kudos to the work done! I would like your inputs to handle the problem I face when downloading the Taichi dataset. 
I work on a Windows machine, the code is being run in a conda environment with all the prescribed packages installed. In an attempt to retrain the model using a different keypoint detector network, I tried downloading the videos for Taichi dataset following the instructions in /data/taichi-loading/README.md and encounter the following error. 

**OSError: [WinError 193] %1 is not a valid Win32 application**
Kindly let me know how to solve this issue. Pasting the full error trace below:
(py37torch) d:\Jo\first-order-model> cd d:\Jo\first-order-model && cmd /C "C:\Anaconda3\envs\artidatagen\python.exe "c:\Users\Divyam Saran\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy\launcher" 59801 -- d:\Jo\first-order-model\data\taichi-loading\load_videos.py "
0it [00:00, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artidatagen\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "d:\Jo\first-order-model\data\taichi-loading\load_videos.py", line 49, in run
    download(video_id.split('#')[0], args)
  File "d:\Jo\first-order-model\data\taichi-loading\load_videos.py", line 41, in download
    video_path], stdout=DEVNULL, stderr=DEVNULL)
  File "C:\Anaconda3\envs\artidatagen\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Anaconda3\envs\artidatagen\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\envs\artidatagen\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
  File "c:\Users\Divyam Saran\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 632, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, cmd_line, *args)
OSError: [WinError 193] %1 is not a valid Win32 application
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\artidatagen\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\artidatagen\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Divyam Saran\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Divyam Saran\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Divyam Saran\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Anaconda3\envs\artidatagen\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Anaconda3\envs\artidatagen\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Anaconda3\envs\artidatagen\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\Jo\first-order-model\data\taichi-loading\load_videos.py", line 118, in <module>
    for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
  File "C:\Anaconda3\envs\artidatagen\lib\site-packages\tqdm\_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "C:\Anaconda3\envs\artidatagen\lib\multiprocessing\pool.py", line 735, in next
    raise value
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by jysa01** [comment]
A workaround can help fix this error. 

1. Install _youtube-dl_ in your environment:
`pip install youtube_dl` 

2. Make the following changes to the file: **load_videos.py** 
`import youtube_dl`

3. Modify the **download** module as follows. This downloads all videos (with an active/ functioning link) into your working directory
```
def download(video_id, args):
    video_path = os.path.join(args.video_folder, video_id + ".mp4")
    ydl_opts = {}
    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        ydl.download(["https://www.youtube.com/watch?v=" + video_id])
    return video_path
```


4. Move them into the youtube-taichi directory(optional). 
5. Modify the names of the downloaded videos to contain only the _video_id_. This is a requirement of the existing code in the **run** module so that the right video can be split and cropped to the required size as listed in _taichi-metadata.csv._ 

This solution worked for me. Kindly add other approaches to this solution here.

**Comment by vatsal278** [comment]
PS E:\video-preprocessing-master> python load_videos.py --metadata vox-metadata.csv --format .png --out_folder vox --workers 1
0it [00:00, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "D:\anaconda\envs\xx\lib\multiprocessing\pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "E:\video-preprocessing-master\load_videos.py", line 32, in run
download(video_id.split('#')[0], args)
File "E:\video-preprocessing-master\load_videos.py", line 25, in download
video_path], stdout=DEVNULL, stderr=DEVNULL)
File "D:\anaconda\envs\xx\lib\subprocess.py", line 247, in call
with Popen(*popenargs, **kwargs) as p:
File "D:\anaconda\envs\xx\lib\subprocess.py", line 676, in init
restore_signals, start_new_session)
File "D:\anaconda\envs\xx\lib\subprocess.py", line 957, in _execute_child
startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "load_videos.py", line 100, in
for chunks_data in tqdm(pool.imap_unordered(run, zip(video_ids, args_list))):
File "D:\anaconda\envs\xx\lib\site-packages\tqdm_tqdm.py", line 1002, in iter
for obj in iterable:
File "D:\anaconda\envs\xx\lib\multiprocessing\pool.py", line 731, in next
raise value
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by vatsal278** [comment]
Adding youtube-dl to path helped me run the code.
PS E:\video-preprocessing-master> python load_videos.py --metadata vox-metadata.csv --format .png --out_folder vox --workers 1 --youtube-dl

**Comment by MihailoGrbic** [comment]
Since you're using windows you need to download youtube-dl.exe from https://youtube-dl.org/ instead of just youtube-dl. You also need to make sure to add the `--youtube .\youtube-dl.exe` argument when running load_videos.py.
