### ISSUE TITLE
Problem with docker build

### ISSUE THREAD

**Issue by aliig** [AliaksandrSiarohin/first-order-model#226]
I'm struggling to get the proper linux environment to work for this, so I've resorted to using docker. I eventually got the program to work with the provided docker build instructions about a week or so ago on WSL2, but it doesn't seem to work for me any more.

`docker build -t first-order-model .` fails for me on this step: [full log](https://pastebin.com/HvBNJrV4)
```
Collecting opencv-python (from face-alignment==1.1.0)
  Downloading https://files.pythonhosted.org/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz (88.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wuc0x2vh/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

Any ideas to get this working again?

Running on a fresh WSL2 Ubuntu build following the instructions [here](https://docs.nvidia.com/cuda/wsl-user-guide/index.html). Building with a fresh clone of this repo as well.

Thank you!

**Comment by koles289** [comment]
Hi, I have exactly the same problem after downloading OpenVino toolkit for linux with FPGA support version 2020.4.287.
the same issue is being solved in this thread, but I do not know, how to download changed files.
https://github.com/OpenVisualCloud/Dockerfiles/issues/549

**Comment by RomanKovtyukh** [comment]
Hi, this problem is described in [issue in official opencv-python repo](https://github.com/skvark/opencv-python/issues/372) and in [their FAQ](https://github.com/skvark/opencv-python#frequently-asked-questions).

**Comment by lobomfz** [comment]
[Submited a pull request to fix it](https://github.com/AliaksandrSiarohin/first-order-model/pull/228)

**Comment by aliig** [comment]
> [Submited a pull request to fix it](https://github.com/AliaksandrSiarohin/first-order-model/pull/228)

This worked, thank you

**Comment by ishc3ice** [comment]
Edit the Dockerfile, and add `RUN pip3 install scikit-build==0.11.1` before the last Command

about like this:

```
FROM nvcr.io/nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update \
 && DEBIAN_FRONTEND=noninteractive apt-get -qqy install python3-pip ffmpeg git less nano libsm6 libxext6 libxrender-dev \
 && rm -rf /var/lib/apt/lists/*

COPY . /app/
WORKDIR /app

RUN pip3 install scikit-build==0.11.1

RUN pip3 install \
  https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl \
  git+https://github.com/1adrianb/face-alignment \
  -r requirements.txt
```
