### ISSUE TITLE
error with skicit?

### ISSUE THREAD

**Issue by grandogarndo** [AliaksandrSiarohin/first-order-model#239]
ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ashis\\AppData\\Local\\Temp\\pip-install-xcj2qcs7\\scikit-image\\setup.py'"'"'; __file__='"'"'C:\\Users\\ashis\\AppData\\Local\\Temp\\pip-install-xcj2qcs7\\scikit-image\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ashis\AppData\Local\Temp\pip-pip-egg-info-2rnicq1f'
         cwd: C:\Users\ashis\AppData\Local\Temp\pip-install-xcj2qcs7\scikit-image\
    Complete output (46 lines):
    Partial import of skimage during the build process.
    Traceback (most recent call last):
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-xcj2qcs7\scikit-image\skimage\_build.py", line 30, in cython
        from Cython import __version__
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-xcj2qcs7\scikit-image\setup.py", line 111, in <module>
        setup(
      File "c:\python38\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-xcj2qcs7\scikit-image\setup.py", line 70, in configuration
        config.add_subpackage('skimage')
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage\setup.py", line 14, in configuration
        config.add_subpackage('feature')
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\python38\lib\site-packages\numpy\distutils\misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "skimage\feature\setup.py", line 22, in configuration
        cython(['_haar.pyx'], working_path=base_path)
      File "C:\Users\ashis\AppData\Local\Temp\pip-install-xcj2qcs7\scikit-image\skimage\_build.py", line 41, in cython
        raise RuntimeError('Cython >= %s is required to build scikit-image from git checkout' \
    RuntimeError: Cython >= 0.23 is required to build scikit-image from git checkout
    Cython >= 0.23 not found; falling back to pre-built geometry.c
    Cython >= 0.23 not found; falling back to pre-built transform.c
    Cython >= 0.23 not found; falling back to pre-built interpolation.c
    Cython >= 0.23 not found; falling back to pre-built _draw.c
    Cython >= 0.23 not found; falling back to pre-built corner_cy.c
    Cython >= 0.23 not found; falling back to pre-built censure_cy.c
    Cython >= 0.23 not found; falling back to pre-built orb_cy.c
    Cython >= 0.23 not found; falling back to pre-built brief_cy.c
    Cython >= 0.23 not found; falling back to pre-built _texture.c
    Cython >= 0.23 not found; falling back to pre-built _hessian_det_appx.c
    Cython >= 0.23 not found; falling back to pre-built _hoghistogram.c
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Picucu** [comment]
install cython first
