### ISSUE TITLE
crop-video.py Permission io read/write problem

### ISSUE THREAD

**Issue by Imikeeee** [AliaksandrSiarohin/first-order-model#240]
H:\something\first-order-model>python3 crop-video.py --inp driving_video/zsebibaba.mp4
Traceback (most recent call last):
  File "crop-video.py", line 1, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'

**Comment by Imikeeee** [comment]
So i managed to solve the prev error but there is an another :

`H:\first-order-model\first-order-model>py crop-video.py --inp driving_video/zsebibaba.mp4
Traceback (most recent call last):
  File "H:\anacondaa\lib\site-packages\imageio\plugins\ffmpeg.py", line 59, in _get_ffmpeg_api
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 87, in process_video
    video = imageio.get_reader(args.inp)
  File "H:\anacondaa\lib\site-packages\imageio\core\functions.py", line 186, in get_reader
    return format.get_reader(request)
  File "H:\anacondaa\lib\site-packages\imageio\core\format.py", line 170, in get_reader
    return self.Reader(self, request)
  File "H:\anacondaa\lib\site-packages\imageio\core\format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "H:\anacondaa\lib\site-packages\imageio\plugins\ffmpeg.py", line 257, in _open
    self._ffmpeg_api = _get_ffmpeg_api()
  File "H:\anacondaa\lib\site-packages\imageio\plugins\ffmpeg.py", line 61, in _get_ffmpeg_api
    raise ImportError(
ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'
`

The imageio-ffmpeg is installed ... even with conda

**Comment by Imikeeee** [comment]
Sooo I managed the prev issue too , but when I run the crop-video.py I got a windows10 popup: This program cannot run on your pc .... and afterthe CMD show this :

` H:\first-order-model\first-order-model>py crop-video.py --inp driving_video/zsebibaba.mp4
Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 87, in process_video
    video = imageio.get_reader(args.inp)
  File "C:\Python38\lib\site-packages\imageio\core\functions.py", line 129, in get_reader
    return format.get_reader(request)
  File "C:\Python38\lib\site-packages\imageio\core\format.py", line 168, in get_reader
    return self.Reader(self, request)
  File "C:\Python38\lib\site-packages\imageio\core\format.py", line 217, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Python38\lib\site-packages\imageio\plugins\ffmpeg.py", line 358, in _open
    self._load_infos()
  File "C:\Python38\lib\site-packages\imageio\plugins\ffmpeg.py", line 523, in _load_infos
    raise IOError(fmt % err2)
OSError: Could not load meta information
=== stderr ===

A hozzfrs megtagadva. ( Acces denied)`
