### ISSUE TITLE
crop-video.py / OMP: Error #15: Initializing libiomp5md.dll

### ISSUE THREAD

**Issue by mertnizamoglu** [AliaksandrSiarohin/first-order-model#267]
Hi everyone,

Today i was try to learn DeepFake Image Animation and than found a [tutorial](https://www.youtube.com/watch?v=AtnjRWjpyfA)

I follow this tutorial step by step. When i came to 24:02 he's entering the `python crop-video.py --inp some_youtube_video.mp4` code. 

and this is my version of this code `(deepfake) F:\DeepFake>python crop-video.py --inp assets/intro.mp4`

but when i run this code 

> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

getting error like this. 

I search a lot of site for that. And i tried this one: https://docs.anaconda.com/mkl-optimizations/

It's passed my error but had an another error :'( and this one;

> Traceback (most recent call last):
  File "crop-video.py", line 1, in <module>
    import face_alignment
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mertn\anaconda3\envs\deepfake\lib\site-packages\face_alignment-1.1.0-py3.8.egg\face_alignment\__init__.py", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mertn\anaconda3\envs\deepfake\lib\site-packages\face_alignment-1.1.0-py3.8.egg\face_alignment\api.py", line 3, in <module>
  File "C:\Users\mertn\anaconda3\envs\deepfake\lib\site-packages\torch\__init__.py", line 97, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

I reinstall the Numpy run again the code;

> (deepfake) F:\DeepFake>python crop-video.py --inp assets/intro.mp4
Traceback (most recent call last):
  File "crop-video.py", line 1, in <module>
    import face_alignment
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mertn\anaconda3\envs\deepfake\lib\site-packages\face_alignment-1.1.0-py3.8.egg\face_alignment\__init__.py", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\mertn\anaconda3\envs\deepfake\lib\site-packages\face_alignment-1.1.0-py3.8.egg\face_alignment\api.py", line 6, in <module>
ModuleNotFoundError: No module named 'skimage'

Skimage is part of that scikit-image (face-alignment requirement)

And then.... run again the code;

> (deepfake) F:\DeepFake>python crop-video.py --inp assets/intro.mp4
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

See? Turn back to nothing... Anyone have solution for that? 

(Sorry if i wrote anything wrong. My english is little problematic :D)

Thanks in advance for your interest.

**Comment by blackcherry0827** [comment]
****

**Comment by slapswan** [comment]
Was this ever resolved? I am having the same issue as described.

**Comment by carlostling** [comment]
I've got the same issue.
