### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken`

### ISSUE THREAD

**Issue by brunodbrazil** [AliaksandrSiarohin/first-order-model#277]
I tried to train, but I have this mistake. What to do?

`Training...
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to C:\Users\xxxxx/.cache\torch\checkpoints\vgg19-dcbb9e9d.pth
100%|██████████████████████████████████████████████████████████████| 574673361/574673361 [00:26<00:00, 21689701.34it/s]
  0%|                                                                                          | 0/150 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "D:\Anaconda\First\train.py", line 50, in train
    for x in dataloader:
  File "C:\Users\XXX\.conda\envs\FIRST\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\XXX\.conda\envs\FIRST\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "C:\Users\XXX\.conda\envs\FIRST\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\UseR\XXX\.conda\envs\FIRST\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Anaconda\First\frames_dataset.py", line 154, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "D:\Anaconda\First\frames_dataset.py", line 103, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken`

**Comment by AliaksandrSiarohin** [comment]
I guess you should set id_sampling: False.
