### ISSUE TITLE
numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by nightsurfer7** [AliaksandrSiarohin/first-order-model#283]
cmd: python crop-video.py --inp source_video/Obama.mp4

Traceback (most recent call last):
  File "crop-video.py", line 1, in <module>
    import face_alignment
  File "/home/nightsurfer/anaconda3/envs/FOM2/lib/python3.6/site-packages/face_alignment/__init__.py", line 7, in <module>
    from .api import FaceAlignment, LandmarksType, NetworkSize
  File "/home/nightsurfer/anaconda3/envs/FOM2/lib/python3.6/site-packages/face_alignment/api.py", line 3, in <module>
    import torch
  File "/home/nightsurfer/anaconda3/envs/FOM2/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

**Comment by lhyfst** [comment]
you should upgrade the numpy version to 1.20.3
