### ISSUE TITLE
Getting "Killed" when running code on PC.

### ISSUE THREAD

**Issue by Vinchethescript** [AliaksandrSiarohin/first-order-model#287]
I want to run this on my Arch x86_x64 PC because I can't be always connected to Internet, and there are moments where I need it.
I tried copy-pasting code on my host, this is the code now:
```python
import imageio
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from skimage.transform import resize
from IPython.display import HTML
from demo import load_checkpoints
from demo import make_animation
from skimage import img_as_ubyte
import warnings
warnings.filterwarnings("ignore")

source_image = imageio.imread('dvf.png')
driving_video = imageio.mimread('bmt.mp4')


#Resize image and video to 256x256

source_image = resize(source_image, (256, 256))[..., :3]
driving_video = [resize(frame, (256, 256))[..., :3] for frame in driving_video]

def display(source, driving, generated=None):
    fig = plt.figure(figsize=(8 + 4 * (generated is not None), 6))

    ims = []
    for i in range(len(driving)):
        cols = [source]
        cols.append(driving[i])
        if generated is not None:
            cols.append(generated[i])
        im = plt.imshow(np.concatenate(cols, axis=1), animated=True)
        plt.axis('off')
        ims.append([im])

    ani = animation.ArtistAnimation(fig, ims, interval=50, repeat_delay=1000)
    plt.close()
    return ani
    

HTML(display(source_image, driving_video).to_html5_video())


generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', 
                            checkpoint_path='vox-cpk.pth.tar')


predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=True)

#save resulting video
imageio.mimsave('generated.mp4', [img_as_ubyte(frame) for frame in predictions])
#video can be downloaded from /content folder

HTML(display(source_image, driving_video, predictions).to_html5_video())
```
Before reading some issues in the repo I was getting the following:
```python
$ py deepfake.py 
/home/vincysuper07/botti_di_capodanno/stockdroidfans/first-order-model/demo.py:2: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "deepfake.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 565, in _read_frame_data
    (len(s), framesize))
RuntimeError: Frame is 0 bytes, but expected 196608.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deepfake.py", line 14, in <module>
    driving_video = imageio.mimread('bmt.mp4')
  File "/usr/local/lib/python3.7/site-packages/imageio/core/functions.py", line 286, in mimread
    for im in reader:
  File "/usr/local/lib/python3.7/site-packages/imageio/core/format.py", line 397, in iter_data
    im, meta = self._get_data(i)
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 396, in _get_data
    result, is_new = self._read_frame()
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 585, in _read_frame
    s, is_new = self._read_frame_data()
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 571, in _read_frame_data
    raise CannotReadFrameError(fmt % (self._pos, err1, err2))
imageio.core.format.CannotReadFrameError: Could not read frame 838:
Frame is 0 bytes, but expected 196608.
=== stderr ===
ffmpeg version N-99269-gcdc4c26 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/home/vincysuper07/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/vincysuper07/ffmpeg_build/include --extra-ldflags=-L/home/vincysuper07/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/vincysuper07/bin --enable-gpl --enable-openssl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 59.100 / 56. 59.100
  libavcodec     58.106.100 / 58.106.100
  libavformat    58. 58.100 / 58. 58.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/vincysuper07/botti_di_capodanno/stockdroidfans/first-order-model/bmt.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.58.100
  Duration: 00:00:28.07, start: 0.000000, bitrate: 263 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 256x256 [SAR 1:1 DAR 1:1], 126 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/03/2020.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/03/2020.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.58.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 256x256 [SAR 1:1 DAR 1:1], q=2-31, 47138 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
ffmpeg version N-99269-gcdc4c26 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --prefix=/home/vincysuper07/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/vincysuper07/ffmpeg_build/include --extra-ldflags=-L/home/vincysuper07/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/vincysuper07/bin --enable-gpl --enable-openssl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 59.100 / 56. 59.100
  libavcodec     58.106.100 / 58.106.100
  libavformat    58. 58.100 / 58. 58.100
  libavdevice    58. 11.102 / 58. 11.102
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/vincysuper07/botti_di_capodanno/stockdroidfans/first-order-model/bmt.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.58.100
  Duration: 00:00:28.07, start: 0.000000, bitrate: 263 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 256x256 [SAR 1:1 DAR 1:1], 126 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/03/2020.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/03/2020.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.58.100
    Stream #0:0(und): Video: rawvideo (RGB[24] / 0x18424752), rgb24, 256x256 [SAR 1:1 DAR 1:1], q=2-31, 47138 kb/s, 29.97 fps, 29.97 tbn, 29.97 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc. Created on: 08/03/2020.
      encoder         : Lavc58.106.100 rawvideo
frame=  443 fps=0.0 q=-0.0 size=   85056kB time=00:00:14.78 bitrate=47138.8kbits/s speed=29.5x    
frame=  839 fps=0.0 q=-0.0 Lsize=  161088kB time=00:00:27.99 bitrate=47138.8kbits/s speed=35.7x    
video:161088kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```
but after reading I replaced `driving_video = imageio.mimread('bmt.mp4')` with the following:
```python
reader = imageio.get_reader('bmt.mp4')
driving_video = []
try:
    for im in reader:
        driving_video.append(im)
except RuntimeError:
    pass
```
When I tried it, though, the output was `Killed`, without the generated file. I tried replacing the same thing in colab and it worked fine. How can I fix this?

**Comment by AliaksandrSiarohin** [comment]
You should use script demo.py, usage is in Readme.

**Comment by Vinchethescript** [comment]
Oh okay, thanks.
