### ISSUE TITLE
How to run demo.py with pytorch 1.0.0 with CPU support

### ISSUE THREAD

**Issue by DurgaPrasadReddyV** [AliaksandrSiarohin/first-order-model#29]
I get the following error:

C:\Users\USER\source\repos\AliaksandrSiarohin\first-order-model>python demo.py --config config/vox-256.yaml --driving_video first-order-motion-model/04.mp4 --source_image first-order-motion-model/05.png --checkpoint first-order-motion-model/vox-cpk.pth.tar --relative --adapt_scale
demo.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
  File "demo.py", line 29, in load_checkpoints
    generator.cuda()
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "C:\Users\USER\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by AliaksandrSiarohin** [comment]
Remove all calls, .cuda(). Lines 29,33,51,52 in demo.py

**Comment by DurgaPrasadReddyV** [comment]
Thank you it worked.

**Comment by simplyexperimental** [comment]
@AliaksandrSiarohin Could you please provide the demo.py file with those lines removed and the correct syntax to get it working for cpu machines for example on line 35 I tried this but I am new to all of this:
checkpoint = torch.load(checkpoint_path, map_location=lambda storage, location: 'cpu')
It doesn't work haha.

**Comment by volksvargas** [comment]
> @AliaksandrSiarohin Could you please provide the demo.py file with those lines removed and the correct syntax to get it working for cpu machines for example on line 35 I tried this but I am new to all of this:
> checkpoint = torch.load(checkpoint_path, map_location=lambda storage, location: 'cpu')
> It doesn't work haha.

checkpoint = torch.load(checkpoint_path, map_location='cpu')
