### ISSUE TITLE
Could not load meta information

### ISSUE THREAD

**Issue by Jak0busus** [AliaksandrSiarohin/first-order-model#301]
Hello.
When I tried to run the demo.py  I got this error :
```
C:\deepfake>python demo.py --config config/vox-adv-256.yaml --driving_video assets/crop.mp4 --source_image assets/torsten.png --checkpoint checkpoint/vox-adv-cpk.pth --relative --adapt_scale
Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    reader = imageio.get_reader(opt.driving_video)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\imageio\core\functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\imageio\core\format.py", line 174, in get_reader
    return self.Reader(self, request)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\imageio\core\format.py", line 224, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\imageio\plugins\ffmpeg.py", line 399, in _open
    self._load_infos()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\imageio\plugins\ffmpeg.py", line 579, in _load_infos
    raise IOError(fmt % err2)
OSError: Could not load meta information
=== stderr ===

The System couldnt find the specified path.
```

The video I used was `https://drive.google.com/drive/folders/1OnNiipQLkvzhiPoQcnZvZBRG4MzL9eih` .

I don't know about python much.

please help!

**Comment by AliaksandrSiarohin** [comment]
This happenes to every video or only to one that your are using?

**Comment by fizzf** [comment]
> 
> 
> This happenes to every video or only to one that your are using?

I have the same problem, I use Fashion dataset, follow the readme.md to train the model and get this error.

**Comment by vibhaa** [comment]
What was the resolution to this issue? I'm facing this after a few epochs on the VoxCeleb dataset.
