### ISSUE TITLE
RAM requirements for demo.py

### ISSUE THREAD

**Issue by reznet** [AliaksandrSiarohin/first-order-model#34]
Hello, what are the RAM requirements for running the demo script?  I have 16GB of ram, but the script failed with a memory error, and I can see in Task Manager that RAM usage was near 100%.  I'm curious how much more RAM I would need to run the script?

I downloaded the `first-order-motion-model` folder into the git repository and ran this command:
`python demo.py --config config\vox-adv-256.yaml --driving_video first-order-motion-model\07.mkv --source_image first-order-motion-model\01.png --checkpoint first-order-motion-model\vox-adv-cpk.pth.tar --relative --adapt_scale`

The error I got was:
```
Traceback (most recent call last):
  File "demo.py", line 119, in <module>
    driving_video = imageio.mimread(opt.driving_video, memtest=False)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\functions.py", line 286, in mimread
    for im in reader:
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\core\format.py", line 397, in iter_data
    im, meta = self._get_data(i)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\plugins\ffmpeg.py", line 396, in _get_data
    result, is_new = self._read_frame()
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\imageio\plugins\ffmpeg.py", line 586, in _read_frame
    result = np.fromstring(s, dtype='uint8')
MemoryError: Unable to allocate 5.93 MiB for an array with shape (6220800,) and data type uint8
```

I'm using Windows 10 with python 3.7

**Comment by AliaksandrSiarohin** [comment]
07.mkv is very not cropped video and it contain many people (video should look like 08.mp4), you can crop video using crop-video.py

**Comment by reznet** [comment]
Thanks for the tip (and for replying to a repo you created a while ago)  I learned about this from [this video](https://www.youtube.com/watch?v=mUfJOQKdtAk) on the 2 Minute Papers channel on YouTube, so expect a few more guests :)

I tried with 08.mp4 and got a different error:

```
C:\Users\mr_j_\source\first-order-model>python demo.py --config config\vox-adv-256.yaml --driving_video first-order-motion-model\08.mp4 --source_image first-order-motion-model\01.png --checkpoint first-order-motion-model\vox-adv-cpk.pth.tar --relative --adapt_scale
C:\Users\mr_j_\AppData\Roaming\Python\Python37\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\mr_j_\AppData\Roaming\Python\Python37\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
Traceback (most recent call last):
  File "demo.py", line 134, in <module>
    predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale)
  File "demo.py", line 53, in make_animation
    kp_source = kp_detector(source)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\source\first-order-model\modules\keypoint_detector.py", line 53, in forward
    feature_map = self.predictor(x)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\source\first-order-model\modules\util.py", line 196, in forward
    return self.decoder(self.encoder(x))
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\source\first-order-model\modules\util.py", line 153, in forward
    outs.append(down_block(outs[-1]))
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\source\first-order-model\modules\util.py", line 110, in forward
    out = self.conv(x)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\mr_j_\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Really, I'm just trying to get the simplest thing working to verify my setup.  Do you have a literal demo command new users could run to generate a working output file?  I.e. which arguments to use for the checkpoint, source, and driving files?  I'm hoping there exists a set of commands I can execute exactly which will generate a good file before I go trying to create my own custom videos.

**Comment by AliaksandrSiarohin** [comment]
You have a problem with cudnn library, I'm not that familiar with windows so not sure what is the problem. The simplest think is to use colab notebok demo.ipynb, you can directly run on google servers without installing any dependency's.

**Comment by reznet** [comment]
Ok, I'm new at python so I'll try the colab notebook next.  BTW, what OS did you use for this?

**Comment by AliaksandrSiarohin** [comment]
I tried in ubuntu 18.04, 16.04, 14.04.

**Comment by reznet** [comment]
Thank you.  I was able to use the google colab and produce my first deep fake!  Thanks for your help!
