### ISSUE TITLE
Error when running crop-video.py

### ISSUE THREAD

**Issue by Gulli03** [AliaksandrSiarohin/first-order-model#351]
When I run crop-video.py on the Video I want to crop it gives this error:

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 96, in process_video
    bboxes =  extract_bbox(frame, fa)
  File "crop-video.py", line 22, in extract_bbox
    bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])
  File "D:\anaconda3\envs\FOM\lib\site-packages\face_alignment-1.3.3-py3.6.egg\face_alignment\detection\sfd\sfd_detector.py", line 44, in detect_from_image
  File "D:\anaconda3\envs\FOM\lib\site-packages\face_alignment-1.3.3-py3.6.egg\face_alignment\detection\sfd\detect.py", line 15, in detect
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)

Any Idea what causes this and how I can fix it?

**Comment by AliaksandrSiarohin** [comment]
What pytorch version you are using?

**Comment by Gulli03** [comment]
I'm using pytorch 1.5.0

**Comment by AliaksandrSiarohin** [comment]
Hmm, weird. Try to rewrite:
```
bboxes = fa.face_detector.detect_from_image(frame[..., [2, 1,0])
```

**Comment by Gulli03** [comment]
After adding a square bracket to the end

`bboxes = fa.face_detector.detect_from_image(frame[..., [2, 1,0]])`

it now works!
Thank you very much!
