### ISSUE TITLE
Training higher resolution on top of vox-256 pretrained model - gives me a size mismatch error

### ISSUE THREAD

**Issue by chloejihye** [AliaksandrSiarohin/first-order-model#359]
Hi @AliaksandrSiarohin! Thank you so much for the great work. I would like to train the model with higher resolution ( 512 x 512 size ), and I checked some people tried it already as I can see it on #14 #81.

It was a bit confusing to me, because it seems like everyone is trying with different values... but anyway following your comment, I changed `kp_detector` resolution to `64` with `scale_factor: 0.125`, and also `dense_motion` `scale_factor` to `0.125`. I also did hardset `sigma = 1.5`.

It is working when I train it from scratch... but I want to know if there is any way **I can train on top of vox-256 pretrained model.**

When I train using vox-256 pretrained model with following command `python run.py --checkpoint checkpoints/vox-cpk.pth.tar --config config/idol-512.yaml --device_ids 0`, it gives me size mismatch error saying that :
 
```
size mismatch for kp.weight: copying a param with shape torch.Size([10, 35, 7, 7]) from checkpoint, the shape in current model is torch.Size([10, 67, 7, 7]).
size mismatch for jacobian.weight: copying a param with shape torch.Size([40, 35, 7, 7]) from checkpoint, the shape in current model is torch.Size([40, 67, 7, 7]).`
```

This is my config file for higher resolution training.

```
dataset_params:
  root_dir: data/idol
  frame_shape: [512, 512, 3]
  id_sampling: False
  pairs_list: data/vox256.csv
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  common_params:
    num_kp: 10
    num_channels: 3
    estimate_jacobian: True
  kp_detector_params:
     temperature: 0.1
     block_expansion: 64
     max_features: 1024
     scale_factor: 0.125
     num_blocks: 5
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.125
  discriminator_params:
    scales: [1]
    block_expansion: 32
    max_features: 512
    num_blocks: 4
    sn: True
```

Whole error message is here : 

``` 
(firstmodel-animation) C:\Users\Administrator\Desktop\first-order\first-order-model>python run.py --checkpoint checkpoints/vox-cpk.pth.tar --config config/idol-512.yaml --device_ids 0
run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Use predefined train-test split.
Training...
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "C:\Users\Administrator\Desktop\first-order\first-order-model\train.py", line 26, in train
    None if train_params['lr_kp_detector'] == 0 else optimizer_kp_detector)
  File "C:\Users\Administrator\Desktop\first-order\first-order-model\logger.py", line 57, in load_cpk
    kp_detector.load_state_dict(checkpoint['kp_detector'])
  File "C:\ProgramData\Anaconda3\envs\firstmodel-animation\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for KPDetector:
        size mismatch for predictor.encoder.down_blocks.0.conv.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3]).
        size mismatch for predictor.encoder.down_blocks.0.conv.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.encoder.down_blocks.0.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.encoder.down_blocks.0.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.encoder.down_blocks.0.norm.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.encoder.down_blocks.0.norm.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.encoder.down_blocks.1.conv.weight: copying a param with shape torch.Size([128, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
        size mismatch for predictor.encoder.down_blocks.1.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.encoder.down_blocks.1.norm.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.encoder.down_blocks.1.norm.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.encoder.down_blocks.1.norm.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.encoder.down_blocks.1.norm.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.encoder.down_blocks.2.conv.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3, 3]).
        size mismatch for predictor.encoder.down_blocks.2.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.encoder.down_blocks.2.norm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.encoder.down_blocks.2.norm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.encoder.down_blocks.2.norm.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.encoder.down_blocks.2.norm.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.encoder.down_blocks.3.conv.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3, 3]).
        size mismatch for predictor.encoder.down_blocks.3.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.encoder.down_blocks.3.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.encoder.down_blocks.3.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.encoder.down_blocks.3.norm.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.encoder.down_blocks.3.norm.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.encoder.down_blocks.4.conv.weight: copying a param with shape torch.Size([1024, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 1024, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.0.conv.weight: copying a param with shape torch.Size([512, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 1024, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.0.conv.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.decoder.up_blocks.0.norm.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.decoder.up_blocks.0.norm.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.decoder.up_blocks.0.norm.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.decoder.up_blocks.0.norm.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([1024]).
        size mismatch for predictor.decoder.up_blocks.1.conv.weight: copying a param with shape torch.Size([256, 1024, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 2048, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.decoder.up_blocks.1.norm.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.decoder.up_blocks.1.norm.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.decoder.up_blocks.1.norm.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.decoder.up_blocks.1.norm.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for predictor.decoder.up_blocks.2.conv.weight: copying a param with shape torch.Size([128, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 1024, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.2.conv.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.decoder.up_blocks.2.norm.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.decoder.up_blocks.2.norm.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.decoder.up_blocks.2.norm.running_mean: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.decoder.up_blocks.2.norm.running_var: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
        size mismatch for predictor.decoder.up_blocks.3.conv.weight: copying a param with shape torch.Size([64, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 512, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.3.conv.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.decoder.up_blocks.3.norm.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.decoder.up_blocks.3.norm.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.decoder.up_blocks.3.norm.running_mean: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.decoder.up_blocks.3.norm.running_var: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for predictor.decoder.up_blocks.4.conv.weight: copying a param with shape torch.Size([32, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 256, 3, 3]).
        size mismatch for predictor.decoder.up_blocks.4.conv.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for predictor.decoder.up_blocks.4.norm.weight: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for predictor.decoder.up_blocks.4.norm.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for predictor.decoder.up_blocks.4.norm.running_mean: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for predictor.decoder.up_blocks.4.norm.running_var: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for kp.weight: copying a param with shape torch.Size([10, 35, 7, 7]) from checkpoint, the shape in current model is torch.Size([10, 67, 7, 7]).
        size mismatch for jacobian.weight: copying a param with shape torch.Size([40, 35, 7, 7]) from checkpoint, the shape in current model is torch.Size([40, 67, 7, 7]).
```

I think there is something wrong with my resolution setting or it's not compatible to train with 256 size pretrained model...? I've also been trying to revise the resolution value and scale_factor value following the existing github issue discussions, but no luck so far.
Your help will be very appreciated.

Thank you very much!

**Comment by chloejihye** [comment]
FYI, it is working when I train it from scratch... I want to know if there is any way I can train on top of vox-256 pretrained model.

**Comment by gemasphi** [comment]
Hey, have you managed to get this working?

**Comment by lincong666** [comment]
how to get the vox256.csv?
