### ISSUE TITLE
Colab: Error train with own dataset

### ISSUE THREAD

**Issue by roli-rk** [AliaksandrSiarohin/first-order-model#366]
I want to train with my own dataset using Colab. But I get this error:
``
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Use predefined train-test split.
Training...
  0% 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/content/drive/MyDrive/BA_FOM/first-order-model/train.py", line 50, in train
    for x in dataloader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/MyDrive/BA_FOM/first-order-model/frames_dataset.py", line 154, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "/content/drive/MyDrive/BA_FOM/first-order-model/frames_dataset.py", line 103, in __getitem__
    path = np.random.choice(glob.glob(os.path.join(self.root_dir, name + '*.mp4')))
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty
``

I realy don't know what I have to change to fix this. Can anyone please give me a tip?

**Comment by AliaksandrSiarohin** [comment]
You should specify id_sampling: False in yaml config.

**Comment by roli-rk** [comment]
thank you. Now it works :)
