### ISSUE TITLE
A ValueError cause that can not crop the video

### ISSUE THREAD

**Issue by MarcHJL** [AliaksandrSiarohin/first-order-model#368]
A ValueError:
```
(FOMM) PS E:\Project\FOMM\first-order-model> python crop-video.py --inp driving_video/video.mp4
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "crop-video.py", line 154, in <module>
    commands = process_video(args)
  File "crop-video.py", line 96, in process_video
    bboxes =  extract_bbox(frame, fa)
  File "crop-video.py", line 22, in extract_bbox
    bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])
  File "E:\Anaconda\envs\FOMM\lib\site-packages\face_alignment-1.3.3-py3.8.egg\face_alignment\detection\sfd\sfd_detector.py", line 45, in detect_from_image
  File "E:\Anaconda\envs\FOMM\lib\site-packages\face_alignment-1.3.3-py3.8.egg\face_alignment\detection\sfd\detect.py", line 15, in detect
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)
```

insert a `frame = frame[...,::-1].copy()` in line 22 ,

and change the origin line 22 from:
`bboxes = fa.face_detector.detect_from_image(frame[..., ::-1])`
to
`bboxes = fa.face_detector.detect_from_image(frame)`
may fix this

**Comment by modbender** [comment]
Same, please do tell if you get how to fix.

**Comment by modbender** [comment]
Ok so for me the problem was that I installed face-alignment using pip/conda, I then cloned the github repo and it worked perfectly. They have not updated the packages on pip and conda. Only repo is up to date.
