### ISSUE TITLE
cropping image

### ISSUE THREAD

**Issue by FurKan7** [AliaksandrSiarohin/first-order-model#38]
Hi there, 
Firstly, your work is awesome. I have to say thank you present that on github.
But, i have a issue when i crop image using crop_image.py. It is showed an error. So, can you tell me what's wrong with that?
 fps = video.get_meta_data()['fps']
KeyError: 'fps'

Thanks

**Comment by AliaksandrSiarohin** [comment]
crop_image.py? Where is this script? I only add crop-video.py. I usually crop images in some simple app like pinta or paint.

**Comment by FurKan7** [comment]
sorry about that. I wanted to say crop_video.py. I considered that we can crop image as well. But i guess i'm wrong.
thanks.

**Comment by zzk88862** [comment]
@AliaksandrSiarohin  hi,  the test image needs to be cropped properly before i excute demo.py,  could you tell me What is the principle of cropping pictures？

**Comment by AliaksandrSiarohin** [comment]
@zzk88862 the principle is that image should be similar to images from train dataset.  See examples  in README.md, neck should be included and shoulders should not.

**Comment by edmar** [comment]
Hey I am getting the same error:

$ python crop-video.py --inp cartoons-01.png

Traceback (most recent call last):
  File "crop-video.py", line 152, in <module>
    commands = process_video(args)
  File "crop-video.py", line 89, in process_video
    fps = video.get_meta_data()['fps']
KeyError: 'fps'

I even used one of the example images cartoons-01.png just to see if the problem was with my image and I get the same error. All images that I used.

**Comment by AliaksandrSiarohin** [comment]
This is for video only.
