### ISSUE TITLE
Hardware GPU requirements

### ISSUE THREAD

**Issue by titusfx** [AliaksandrSiarohin/first-order-model#40]
Hi, I follow the steps to running it locally.

I'm getting the following error

```bash
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/.local/lib/python3.6/site-packages/imageio/core/format.py:403: UserWarning: Could not read last frame of /home/Projects/IA/first-order-model/crop.mp4.
  warn('Could not read last frame of %s.' % uri)
/home/.local/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/.local/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
  File "demo.py", line 35, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "/home.local/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/.local/lib/python3.6/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
  File "/home/.local/lib/python3.6/site-packages/torch/serialization.py", line 504, in persistent_load
    data_type(size), location)
  File "/home/.local/lib/python3.6/site-packages/torch/serialization.py", line 113, in default_restore_location
    result = fn(storage, location)
  File "/home/.local/lib/python3.6/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/.local/lib/python3.6/site-packages/torch/_utils.py", line 76, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 1.96 GiB total capacity; 794.95 MiB already allocated; 17.06 MiB free; 1.05 MiB cached)
(myenv-first-order-model)
```
when execute the following

` python demo.py  --config config/vox-adv-256.yaml --driving_video crop.mp4 --source_image sabri.JPG --checkpoint "/media/Projects/IA/first-order-model-checkpoints/vox-adv-cpk.pth.tar" --relative --adapt_scale`

**Comment by titusfx** [comment]
I try
```python
import torch
checkpoint = torch.load('/media/projects/IA/first-order-model/vox-adv-cpk.pth.tar')
```

And works perfectly
