### ISSUE TITLE
RuntimeError: inverse: For batch 0: U(977224192,977224192) is zero, singular U.

### ISSUE THREAD

**Issue by ethereor** [AliaksandrSiarohin/first-order-model#430]
Great work Aliaksandr!!!
I'm trying to get the demo running locally however when using the nvidia-docker steps provided in the description I encounter the following error, after about 10-15 minutes. I'm using a 256x256 png and video from video-preprocessing script for vox. 

```
~/workspace/first-order-model$ docker run -it --rm --gpus all -v $HOME/workspace/first-order-model:/app first-order-model python3 demo.py --config config/vox-256.yaml --driving_video test.mp4 --source_image test1.png --checkpoint vox-cpk.pth.tar --result_video result.mp4 --relative --adapt_scale

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
  0%|                                                                                                                                                       | 0/58 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 155, in <module>
    predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale, cpu=opt.cpu)
  File "demo.py", line 74, in make_animation
    use_relative_jacobian=relative, adapt_movement_scale=adapt_movement_scale)
  File "/app/animate.py", line 33, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: inverse: For batch 0: U(977224192,977224192) is zero, singular U.
```
I'm not seeing the error here, is there any known problem or a workaround to pass this?

**Comment by AliaksandrSiarohin** [comment]
Is it working on colab?

**Comment by XiaoHuiHua** [comment]
@AliaksandrSiarohin Hello, I also encountered the above problem. I am running on a local Windows 10 computer (GPU RTX 3060, CDUA10, CUDN7.5.0, Python 3.6). Is there any way to solve this problem?

**Comment by quavaro** [comment]
Hi All, I also had the same issue, working in WSL2 with the nvidia-docker steps. It runs for 10-15 minutes then gives 

`File "/app/animate.py", line 33, in normalize_kp
    jacobian_diff = torch.matmul(kp_driving['jacobian'], torch.inverse(kp_driving_initial['jacobian']))
RuntimeError: inverse: For batch 0: U(745161216,745161216) is zero, singular U.` 

I tried the same files in the new and old demo Colabs, and I eventually got it working in the old demo Colab.

**Comment by superwhyun** [comment]
This error seems to occur using a 30xx video card. Just update python(>=3.8) and pytorch(1.12.1). It works like a charm.

**Comment by yangqing-yq** [comment]
I met this issue too. My hardware is RTX 3090ti, ubuntu20.04. torch 1.0.0.
Is this any solution on it?
