### ISSUE TITLE
--cpu mode causes runtime error

### ISSUE THREAD

**Issue by kct22aws** [AliaksandrSiarohin/first-order-model#495]
I tried running `demo.py` with `--cpu` flag. But I get the following runtime error. Here is the command:
`python demo.py  --config config/vox-256.yaml  --driving_video ~/mywork/first-order-model/crop.mp4 --source_image ~/mywork/first-order-model/source-image.jpeg --checkpoint ~/mywork/yadisk-direct/first-order-model/vox-cpk.pth.tar  --relative --adapt_scale --cpu`

And here is the error output:

demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)

Traceback (most recent call last):
  File "demo.py", line 173, in <module>
    predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale, cpu=opt.cpu)
  File "demo.py", line 64, in make_animation
    kp_source = kp_detector(source)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Wombo2/first-order-model/modules/keypoint_detector.py", line 51, in forward
    x = self.down(x)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/Wombo2/first-order-model/modules/util.py", line 242, in forward
    out = F.conv2d(out, weight=self.weight, groups=self.groups)
RuntimeError: std::exception

**Comment by ayush431** [comment]
are you able to test it out with pre trained models??

**Comment by rosklyar** [comment]
> I tried running `demo.py` with `--cpu` flag. But I get the following runtime error. Here is the command: `python demo.py --config config/vox-256.yaml --driving_video ~/mywork/first-order-model/crop.mp4 --source_image ~/mywork/first-order-model/source-image.jpeg --checkpoint ~/mywork/yadisk-direct/first-order-model/vox-cpk.pth.tar --relative --adapt_scale --cpu`
> 
> And here is the error output:
> 
> demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. config = yaml.load(f)
> 
> Traceback (most recent call last): File "demo.py", line 173, in predictions = make_animation(source_image, driving_video, generator, kp_detector, relative=opt.relative, adapt_movement_scale=opt.adapt_scale, cpu=opt.cpu) File "demo.py", line 64, in make_animation kp_source = kp_detector(source) File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in **call** result = self.forward(*input, **kwargs) File "/home/ubuntu/Wombo2/first-order-model/modules/keypoint_detector.py", line 51, in forward x = self.down(x) File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in **call** result = self.forward(*input, **kwargs) File "/home/ubuntu/Wombo2/first-order-model/modules/util.py", line 242, in forward out = F.conv2d(out, weight=self.weight, groups=self.groups) RuntimeError: std::exception

You can just change it to config = yaml.load(f, Loader=yaml.Loader) or downgrade version of yaml parser
