### ISSUE TITLE
kp_detector dimension mismatch in concatenation. 

### ISSUE THREAD

**Issue by JonathanMaluf** [AliaksandrSiarohin/first-order-model#50]
Hi,
While training the model, I run into a dimension match error in the UNet where the layers are being concatenated.
the error:
```
out = torch.cat([out, skip], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 7 and 6 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83
```
What could be causing this mismatch?

**Comment by AliaksandrSiarohin** [comment]
Specify what coomand are you running and full stack trace.

**Comment by JonathanMaluf** [comment]
Hi,
Here is the full output with the command at the top:

The only changes I made to the vox-256 config was the number of blocks (for the kp_detector) and the batch size. 

```
$ CUDA_VISIBLE_DEVICES=0 python3 run.py --config config/vox-256.yaml --device_ids 0

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Use predefined train-test split.
Training...
  0%|                                                                                                                                                  
| 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 77, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/home/ulysses/first-order-model/train.py", line 51, in train
    losses_generator, generated = generator_full(x)
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ulysses/first-order-model/modules/model.py", line 152, in forward
    kp_source = self.kp_extractor(x['source'])
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ulysses/first-order-model/modules/keypoint_detector.py", line 53, in forward
    feature_map = self.predictor(x)
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ulysses/first-order-model/modules/util.py", line 197, in forward
    return self.decoder(self.encoder(x))
  File "/home/ulysses/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ulysses/first-order-model/modules/util.py", line 181, in forward
    out = torch.cat([out, skip], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 7 and 6 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:83
```

**Comment by AliaksandrSiarohin** [comment]
What number of blocks you chose?
What dataset you use? Is all the images are of the same size? Which size?

**Comment by JonathanMaluf** [comment]
I was able to fix the error by using the default video size of 256x256. 
My dataset had  image sizes of 250x250, even though I specified the change in the config file.

Is there a reason that only 256x256 works?

**Comment by AliaksandrSiarohin** [comment]
Unet architecture cannot handle inputs that is not divisible by the 2**num_blocks. Because skip connections assume that the sizes of feature maps is the same.
