### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Adugna233** [AliaksandrSiarohin/first-order-model#547]
run.py:40: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Use predefined train-test split.
Training...
  0%|                                                    | 0/10 [00:00<?, ?it/s]THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=8 : invalid device function
  0%|                                                    | 0/10 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 81, in <module>
    train(config, generator, discriminator, kp_detector, opt.checkpoint, log_dir, dataset, opt.device_ids)
  File "/home/cvlab/Documents/deepfake/train.py", line 51, in train
    losses_generator, generated = generator_full(x)
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/Documents/deepfake/modules/model.py", line 152, in forward
    kp_source = self.kp_extractor(x['source'])
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/Documents/deepfake/modules/keypoint_detector.py", line 53, in forward
    feature_map = self.predictor(x)
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/Documents/deepfake/modules/util.py", line 196, in forward
    return self.decoder(self.encoder(x))
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/Documents/deepfake/modules/util.py", line 153, in forward
    outs.append(down_block(outs[-1]))
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/Documents/deepfake/modules/util.py", line 110, in forward
    out = self.conv(x)
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cvlab/anaconda3/envs/deepfake/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by funboomen** [comment]
i have the same problem

**Comment by funboomen** [comment]
I fix it.
The problem is that the torch version is too old.
Select the compatible versions of Torch and Torchvision according to your CUDA version.

**Comment by Adugna233** [comment]
thank you.
