### ISSUE TITLE
error installing avatarify 

### ISSUE THREAD

**Issue by king4671** [AliaksandrSiarohin/first-order-model#596]
after installation and i run window.bat this is the error codes i keep gettingcan i get some help here please 
(avatarify) C:\Users\DAWUD\avatarify>run_windows.bat
[1730595183.692813] Loading Predictor
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 216, in <module>
    from afy import predictor_local
  File "C:\Users\DAWUD\avatarify\afy\predictor_local.py", line 4, in <module>
    from modules.keypoint_detector import KPDetector
ModuleNotFoundError: No module named 'modules.keypoint_detector'; 'modules' is not a package

**Comment by RYG81** [comment]
yes please help I am getting same issue. I'm trying to port this to comfy Ui node.
