### ISSUE TITLE
Is an NVIDIA GPU Required?

### ISSUE THREAD

**Issue by Aroloss** [AliaksandrSiarohin/first-order-model#60]
I ran the demo.py script and got this error. (Windows, Python 3.7)

C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
demo.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
  File "demo.py", line 29, in load_checkpoints
    generator.cuda()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError:
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

If a NVIDIA GPU is required am I able to run this off of my CPU?

**Comment by ZeroCool940711** [comment]
@Aroloss Check this comment made by AliaksandrSiarohin [on this issue](https://github.com/AliaksandrSiarohin/first-order-model/issues/29#issuecomment-605514978). Keep in mind that the line number might have changed a bit as a few lines were added to the top of the file.

**Comment by Aroloss** [comment]
I followed the comment by AliaksandrSiarohin to remove the .cuda() calls, but this error occurred. Any help is greatly appreciated. Thanks so much.

C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
demo.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint)
  File "demo.py", line 35, in load_checkpoints
    checkpoint = torch.load(checkpoint_path)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 538, in _load
    result = unpickler.load()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 504, in persistent_load
    data_type(size), location)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 113, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 94, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 78, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

**Comment by AliaksandrSiarohin** [comment]
Added cpu mode for demo.py. Add --cpu.
