### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by Jessicall** [AliaksandrSiarohin/first-order-model#93]
Traceback (most recent call last):
  File "demo.py", line 131, in <module>
    source_image = imageio.imread(opt.source_image)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.6/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/usr/local/miniconda3/envs/animation1/lib/python3.6/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename
ValueError: Could not find a format to read the specified file in single-image mode

when i run the command,iget the above error
python demo.py --config config/fashion-256.yaml --driving_video path/to/driving --source_image path/to/source --checkpoint path/to/checkpoint --relative --adapt_scale

**Comment by AliaksandrSiarohin** [comment]
You should provide an image as source. Png or jpg
