### ISSUE TITLE
Run demo with CPU for machine with no GPU?

### ISSUE THREAD

**Issue by JackWetherell** [AliaksandrSiarohin/first-order-model#99]
I am attempting to run the demo and I get the following error:
`python demo.py  --config config/vox-256.yaml --driving_video video.mp4 --source_image image.jpg --checkpoint vox-cpk.pth.tar --relative --adapt_scale
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING:root:Warning: the frame size for reading (1080, 1920) is different from the source frame size (1920, 1080).
WARNING:root:Warning: the frame size for reading (1080, 1920) is different from the source frame size (1920, 1080).
/home/jack/.local/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/home/jack/.local/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "demo.py", line 139, in <module>
    generator, kp_detector = load_checkpoints(config_path=opt.config, checkpoint_path=opt.checkpoint, cpu=opt.cpu)
  File "demo.py", line 32, in load_checkpoints
    generator.cuda()
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/jack/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/jack/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/home/jack/.local/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
`
My machine does not have a GPU, is it possible to use the CPU, and if so how?
Many Thanks.

**Comment by JackWetherell** [comment]
I have found this is solved by adding the `--cpu` flag.

**Comment by chayakornjj** [comment]
I had try to use --cpu but seem like it said
`demo.py: error: unrecognized arguments: --cpu` 

Any recommendation for this one?

**Comment by AliaksandrSiarohin** [comment]
Update. 

> I had try to use --cpu but seem like it said
> `demo.py: error: unrecognized arguments: --cpu`
> 
> Any recommendation for this one?
